@base_url = http://localhost

@port = 8085

@url = {{base_url}}:{{port}}  

@sensors_api = {{url}}/sensors



###
GET {{sensors_api}} HTTP/1.1

###
POST {{sensors_api}} HTTP/1.1
Content-Type: application/json 

{
    "node_id":"1",
    "node_name":"MYHOME",
    "memory_size":"2024",
    "temperature_value":"200",
    "humidity_value":"200",
    "pressure_value":"200"
}

###
GET {{sensors_api}}/Surgery Room 1 HTTP/1.1

###
DELETE  {{sensors_api}}/MYHOME HTTP/1.1

###
GET {{sensors_api}}/all/ HTTP/1.1